version: "3.8"

volumes:
  master-data:
  replica-data:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: "1m"
      max-file: "10"

services:
  master:
    <<: *common
    build: ./postgres
    image: postgres:10.19-rep
    environment:
      COMPOSE_PROJECT_NAME:
      POSTGRES_PASSWORD:
    container_name: ${COMPOSE_PROJECT_NAME}-master
    networks:
      default:
    volumes:
      - master-data:/var/lib/postgresql/data

  replica:
    <<: *common
    build: ./postgres
    image: postgres:10.19-rep
    environment:
      COMPOSE_PROJECT_NAME:
      POSTGRES_PASSWORD:
    container_name: ${COMPOSE_PROJECT_NAME}-replica
    networks:
      default:
    volumes:
      - replica-data:/var/lib/postgresql/data
